# Generated by Django 2.0.2 on 2019-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190114_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='article.Tag'),
        ),
    ]
