# Generated by Django 2.0.2 on 2019-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190114_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantdict',
            name='app',
            field=models.TextField(null=True),
        ),
    ]
