# Generated by Django 2.0.2 on 2019-01-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190114_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantdict',
            name='_type',
            field=models.TextField(choices=[('NUMBER', 'NUMBER'), ('TEXT', 'TEXT')]),
        ),
        migrations.AlterField(
            model_name='constantdict',
            name='app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constantdict',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_constantdict_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constantdict',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_constantdict_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_navbaritem_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_navbaritem_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
